---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "iot-frontend-config"
  namespace: "default"
  labels:
    app: "iot-frontend"
data:
  BACKEND_HOST: "35.228.144.8"
  BACKEND_PORT: "80"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "iot-frontend"
  namespace: "default"
  labels:
    app: "iot-frontend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "iot-frontend"
  template:
    metadata:
      labels:
        app: "iot-frontend"
    spec:
      containers:
      - name: "frontend-server"
        image: "eu.gcr.io/fwardz001-poc-ci1s/frontend_server:latest"
        env:
        - name: "BACKEND_HOST"
          valueFrom:
            configMapKeyRef:
              key: "BACKEND_HOST"
              name: "iot-frontend-config"
        - name: "BACKEND_PORT"
          valueFrom:
            configMapKeyRef:
              key: "BACKEND_PORT"
              name: "iot-frontend-config"
