---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "iot-backend2-service"
  namespace: "default"
  labels:
    app: "iot-backend2"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5050
  selector:
    app: "iot-backend2"
  type: "LoadBalancer"
  loadBalancerIP: ""