---
apiVersion: v1
kind: Service
metadata:
  name: iot-backend-mariadb-svc
  labels:
    app: iot-backend
spec:
  ports:
    - port: 3306
  selector:
    app: iot-backend
    tier: mariadb
  clusterIP: None