apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rest-api-agent-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: iot-backend-rest-api-agent
      tier: rest-api-agent
  policyTypes:
  - Ingress