site_name: Hybrid Cloud IoT App

repo_url: https://github.com/pradeesi/HybridCloudApp/tree/master/HybridCloudApp/Documentation/

nav:
  - AWS IoT Core Configuration: 'AWS_IoT.md'
  - Raspberry Pi with Humidity and Temperature Sensor Configuration: 'RaPi_with_Sensor.md'